function toCamel(row) {
  return {
    id: row.id,
    ownerId: row.owner_id,
    type: row.type,
    category: row.category,
    title: row.title,
    vendor: row.vendor,
    vendorOffice: row.vendor_office,
    location: row.location,
    mapLink: row.map_link,
    description: row.description,
    includes: row.includes,
    priceValue: row.price_value,
    currency: row.currency,
    priceLabel: row.price_label,
    offPeakValue: row.off_peak_value,
    offPeakLabel: row.off_peak_label,
    season: row.season,
    image: row.image,
    keywords: row.keywords,
    commissionRate: row.commission_rate,
    createdAt: row.created_at,
  };
}
